name: BetterRepair
version: '${project.version}'
main: it.samuconfaa.betterrepair.BetterRepair
depend: [Vault]
commands:
  fix:
    description: Comando principale per riparare oggetti e ricaricare la configurazione.
    usage: /<command> [reload]
    aliases: [repair]
    permission: fix.use
permissions:
  fix.reload:
    description: Permette di ricaricare la configurazione
    default: op